name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder elfutils
          flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: npm ci
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux -- --publish never
        env:
          DEBUG: "@malept/flatpak-bundler,electron-installer-flatpak,electron-builder*"

      - uses: actions/setup-python@v5
        if: matrix.os == 'windows-latest'
        with:
          python-version: '3.12'

      - name: Install EVS
        if: matrix.os == 'windows-latest'
        run: python -m pip install --upgrade castlabs-evs

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win -- --publish never
        env:
          EVS_ACCOUNT_NAME: ${{ secrets.EVS_ACCOUNT_NAME }}
          EVS_PASSWD: ${{ secrets.EVS_PASSWD }}

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.flatpak
            dist/*.exe
          draft: true
          generate_release_notes: true